name:                aoc2015
version:             0.1.0.0
description:         My solutions for Advent of Code 2015
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              Nick-Chapman/aoc2015.git

dependencies:
- base >= 4.7 && < 5
- bytestring
- clock
- containers
- MissingH

default-extensions:
- DuplicateRecordFields
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- NumericUnderscores
- ScopedTypeVariables
- TypeApplications
- ImportQualifiedPost

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing

library:
  source-dirs: src

executables:
  main.exe:
    main:                app/main.hs
    dependencies:        aoc2015
